# Generated by Django 4.2.16 on 2024-10-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_importantarticles_make_alter_articles_options_memes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='make',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='news.make', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип'),
        ),
    ]
