# Generated by Django 4.2.16 on 2024-10-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_make_options_alter_make_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='name',
        ),
        migrations.AlterField(
            model_name='articles',
            name='make',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='news.make', verbose_name='Соси'),
        ),
    ]
