# Generated by Django 4.2.16 on 2024-10-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_articles_name_alter_articles_make'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportantArticles',
            new_name='inews',
        ),
    ]
