# Generated by Django 4.2.16 on 2024-10-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_importantarticles_inews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='memes',
        ),
    ]
