# Generated by Django 4.2.16 on 2024-10-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_delete_memes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inews',
            options={'verbose_name': 'Важную новость', 'verbose_name_plural': 'Важные Новости'},
        ),
    ]
