# Generated by Django 4.2.16 on 2024-10-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_inews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.make', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tittle',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
