# Generated by Django 4.2.16 on 2024-10-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_articles_image_alter_articles_anons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
