# Generated by Django 4.2.16 on 2024-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_uploadfiles_alter_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/static/news/img/%Y/%m/%d'),
        ),
    ]
