# Generated by Django 4.2.16 on 2024-10-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_articles_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFiles',
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
