# Generated by Django 4.2.16 on 2024-10-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_delete_uploadfiles_alter_articles_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFiles',
            new_name='UploadFiles',
        ),
    ]
