# Generated by Django 4.2.16 on 2024-10-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_uploadedfiles_uploadfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFiles',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image',
        ),
    ]
